import { Event } from "@/types";

export const FAKE_EVENTS: Event[] = [
  {
    id: "1",
    title: "Gibonni Live",
    description: "Nezaboravan koncert",
    city: "Zagreb",
    location: { lat: 45.815, lng: 15.982, address: "Dom sportova" },
    date: new Date(),
    imageUrl: "",
    category: "koncerti",
    price: "25 €",
    createdBy: "admin",
    createdAt: new Date(),
    isFeatured: true,
  },
  {
    id: "2",
    title: "Street Food Festival",
    description: "Najbolja hrana u gradu",
    city: "Zagreb",
    location: { lat: 45.813, lng: 15.977, address: "Zrinjevac" },
    date: new Date(),
    imageUrl: "",
    category: "festivali",
    price: "Besplatno",
    createdBy: "admin",
    createdAt: new Date(),
    isFeatured: false,
  },
  {
    id: "3",
    title: "Pub Kviz — The Pub",
    description: "Tjedni pub kviz",
    city: "Zagreb",
    location: { lat: 45.812, lng: 15.981, address: "The Pub" },
    date: new Date(),
    imageUrl: "",
    category: "pub-kvizovi",
    price: "Besplatno",
    createdBy: "admin",
    createdAt: new Date(),
    isFeatured: false,
  },
  {
    id: "4",
    title: "Techno Night — Shelter",
    description: "Najbolji techno u gradu",
    city: "Zagreb",
    location: { lat: 45.811, lng: 15.979, address: "Shelter Club" },
    date: new Date(),
    imageUrl: "",
    category: "klubovi",
    price: "10 €",
    createdBy: "admin",
    createdAt: new Date(),
    isFeatured: false,
  },
];
